/*
 * YAi!
 *
 * Copyright © 2019-2026 UmbertoGiacobbiDotBiz. All rights reserved.
 * Website: https://umbertogiacobbi.biz
 * Email: hello@umbertogiacobbi.biz
 *
 * This file is part of YAi!.
 *
 * YAi! is free software: you can redistribute it and/or modify it under the terms
 * of the GNU Affero General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * YAi! is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with YAi!. If not, see <https://www.gnu.org/licenses/>.
 *
 * YAi.Client.CLI
 * Dreams Review screen: inspect, promote, and reject dream proposals
 */

#region Using directives

using Spectre.Console;
using YAi.Persona.Models;
using YAi.Persona.Services;

#endregion

namespace YAi.Client.CLI.Screens;

/// <summary>
/// Interactive screen for reviewing pending dream proposals generated by
/// <see cref="DreamingService"/>.  The user can promote a proposal to permanent memory
/// or reject it.
/// </summary>
public sealed class DreamsReviewScreen : Screen
{
    #region Fields

    private readonly PromotionService _promotion;

    #endregion

    #region Constructor

    /// <summary>
    /// Initializes a new instance of the <see cref="DreamsReviewScreen"/> class.
    /// </summary>
    /// <param name="promotion">The promotion service used to promote or reject proposals.</param>
    public DreamsReviewScreen (PromotionService promotion)
    {
        _promotion = promotion ?? throw new ArgumentNullException (nameof (promotion));
    }

    #endregion

    #region Screen implementation

    /// <inheritdoc/>
    public override async Task RunAsync ()
    {
        Console.Clear ();
        AnsiConsole.Clear ();
        Console.Write ("\x1b[3J");
        await new Banner ().RunAsync ();
        AnsiConsole.WriteLine ();

        AnsiConsole.MarkupLine ("[bold magenta]Review Dreams[/]");
        AnsiConsole.MarkupLine ("[grey]Promote or reject proposals generated by the dreaming reflection pass.[/]");
        AnsiConsole.WriteLine ();

        IReadOnlyList<ExtractionCandidate> proposals = await _promotion.GetPendingProposalsAsync();

        if (proposals.Count == 0)
        {
            AnsiConsole.MarkupLine ("[grey]No pending proposals found in candidates.jsonl.[/]");
            AnsiConsole.MarkupLine ("[grey]Run [bold]--dream[/] first to generate new proposals.[/]");
            AnsiConsole.WriteLine ();
            AnsiConsole.MarkupLine ("[grey]Press any key to return...[/]");
            Console.ReadKey (intercept: true);

            return;
        }

        // Summary table
        Table table = new Table ()
            .RoundedBorder ()
            .BorderColor (Color.MediumPurple)
            .AddColumn (new TableColumn ("#").Centered ())
            .AddColumn ("Type")
            .AddColumn ("Content")
            .AddColumn (new TableColumn ("Conf.").RightAligned ());

        for (int i = 0; i < proposals.Count; i++)
        {
            ExtractionCandidate p = proposals[i];
            string preview = p.Content.Length > 90 ? p.Content [..90] + "…" : p.Content;

            table.AddRow (
                (i + 1).ToString (),
                $"[dim]{Markup.Escape(p.EventType)}[/]",
                Markup.Escape (preview),
                $"{p.Confidence:P0}");
        }

        AnsiConsole.Write (table);
        AnsiConsole.WriteLine ();

        // Build selection choices
        List<string> choices = [];

        for (int i = 0; i < proposals.Count; i++)
        {
            string preview = proposals [i].Content.Length > 60
                ? proposals [i].Content [..60] + "…"
                : proposals [i].Content;
            choices.Add($"{i + 1}. [{proposals[i].EventType}] {preview}");
        }

        choices.Add ("Back");

        await ReviewLoopAsync (proposals, choices);
    }

    #endregion

    #region Private — review loop

    private async Task ReviewLoopAsync(IReadOnlyList<ExtractionCandidate> proposals, List<string> choices)
    {
        while (true)
        {
            string selection = AnsiConsole.Prompt (
                new SelectionPrompt<string> ()
                    .Title ("[grey]Select a proposal to review, or [bold]Back[/] to exit:[/]")
                    .PageSize (15)
                    .AddChoices (choices));

            if (selection == "Back")
                return;

            int selectedIndex = choices.IndexOf (selection);

            if (selectedIndex < 0 || selectedIndex >= proposals.Count)
                return;

            ExtractionCandidate chosen = proposals[selectedIndex];

            // Detail panel
            Console.Clear ();
            AnsiConsole.Clear ();
            Console.Write ("\x1b[3J");
            await new Banner ().RunAsync ();
            AnsiConsole.WriteLine ();

            string rationale = chosen.Metadata.GetValueOrDefault("rationale", string.Empty);

            AnsiConsole.Write (
                new Panel (
                    $"[bold]Type:[/] {Markup.Escape(chosen.EventType)}\n" +
                    $"[bold]Content:[/] {Markup.Escape (chosen.Content)}\n" +
                    $"[bold]Rationale:[/] {Markup.Escape(rationale)}\n" +
                    $"[bold]Confidence:[/] {chosen.Confidence:P0}")
                .Header ("[magenta]Dream Proposal[/]")
                .RoundedBorder ()
                .BorderColor (Color.MediumPurple));

            AnsiConsole.WriteLine ();

            string action = AnsiConsole.Prompt (
                new SelectionPrompt<string> ()
                    .Title ("[grey]What would you like to do with this proposal?[/]")
                    .AddChoices ("Promote", "Reject", "Back"));

            if (action == "Back")
            {
                // Re-render the list by returning to the top-level loop
                Console.Clear ();
                AnsiConsole.Clear ();
                Console.Write ("\x1b[3J");
                await new Banner ().RunAsync ();
                AnsiConsole.WriteLine ();

                continue;
            }

            if (action == "Promote")
            {
                PromotionResult result = await _promotion.PromoteAsync (chosen);

                if (result.Success)
                    AnsiConsole.MarkupLine ($"[springgreen2]✔ Promoted:[/] {Markup.Escape (chosen.Content)}");
                else
                    AnsiConsole.MarkupLine ($"[yellow]⚠ Blocked:[/] {Markup.Escape (result.BlockedReason ?? "Unknown reason")}");
            }
            else if (action == "Reject")
            {
                await _promotion.RejectAsync(chosen);
                AnsiConsole.MarkupLine ($"[grey]✖ Rejected:[/] {Markup.Escape (chosen.Content)}");
            }

            AnsiConsole.WriteLine ();
            AnsiConsole.MarkupLine ("[grey]Press any key to continue...[/]");
            Console.ReadKey (intercept: true);

            // Refresh proposals list
            IReadOnlyList<ExtractionCandidate> refreshed = await _promotion.GetPendingProposalsAsync();

            if (refreshed.Count == 0)
            {
                AnsiConsole.MarkupLine ("[grey]All proposals reviewed.[/]");
                AnsiConsole.MarkupLine ("[grey]Press any key to return...[/]");
                Console.ReadKey (intercept: true);

                return;
            }

            // Rebuild choices
            choices.Clear ();

            for (int i = 0; i < refreshed.Count; i++)
            {
                string preview = refreshed [i].Content.Length > 60
                    ? refreshed [i].Content [..60] + "…"
                    : refreshed [i].Content;
                choices.Add($"{i + 1}. [{refreshed[i].EventType}] {preview}");
            }

            choices.Add ("Back");

            // Update proposals reference for next iteration
            proposals = refreshed;

            Console.Clear ();
            AnsiConsole.Clear ();
            Console.Write ("\x1b[3J");
            await new Banner ().RunAsync ();
            AnsiConsole.WriteLine ();

            // Rebuild table
            Table table = new Table ()
                .RoundedBorder ()
                .BorderColor (Color.MediumPurple)
                .AddColumn (new TableColumn ("#").Centered ())
                .AddColumn ("Type")
                .AddColumn ("Content")
                .AddColumn (new TableColumn ("Conf.").RightAligned ());

            for (int i = 0; i < refreshed.Count; i++)
            {
                ExtractionCandidate p = refreshed[i];
                string preview = p.Content.Length > 90 ? p.Content [..90] + "…" : p.Content;

                table.AddRow (
                    (i + 1).ToString (),
                    $"[dim]{Markup.Escape(p.EventType)}[/]",
                    Markup.Escape (preview),
                    $"{p.Confidence:P0}");
            }

            AnsiConsole.Write (table);
            AnsiConsole.WriteLine ();
        }
    }

    #endregion
}
